apiVersion: v1
kind: Service
metadata:
  name: basic-app-service
spec:
  selector:
    app: basic-app
  ports:
  - protocol: TCP
    port: 3000        # ClusterIP service port
    targetPort: 3000  # Pod containerPort
    # nodePort: 30001 # External NodePort  # if we are using type: NodePort, uncomment this
    # nodePort range must be between 30000 and 32767
  type: LoadBalancer
  # type: NodePort
