apiVersion: v1
kind: Service
metadata:
  name: basic-app-service
spec:
  selector:
    app: basic-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    # nodePort: 30001 # You can specify any available port here.  # if we are using type: NodePort
  type: LoadBalancer
  # type: NodePort
