apiVersion: v1
kind: Service
metadata:
  name: express-app-service
spec:
  type: LoadBalancer 
  ports:
    - port: 3000      # Port exposed internally to Pods.
      targetPort: 3000 # Port that containers listen on.
  selector:
    app: express-app  
