apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  db-url: bW9uZ29kYjovL2RldjpkZXZAbW9uZ286MjcwMTcvZGV2  # Base64 encoded value

# echo -n 'mongodb://dev:dev@mongo:27017/dev' | base64